export const hitDice = {
  Barbarian: 12,
  Bard: 8,
  Cleric: 8,
  Druid: 8,
  Fighter: 10,
  Monk: 8,
  Paladin: 10,
  Ranger: 10,
  Rogue: 8,
  Sorcerer: 6,
  Warlock: 8,
  Wizard: 6,
}
export const chrClasses = ['Bard', 'Sorcerer', 'Paladin', 'Warlock']
export const wisClasses = ['Cleric', 'Druid', 'Ranger']
export const statNames = ['STR', 'CON', 'DEX', 'WIS', 'INT', 'CHR']

export const classes = [
  'Barbarian',
  'Fighter',
  'Rogue',
  'Monk',
  'Bard',
  'Cleric',
  'Sorcerer',
  'Wizard',
  'Druid',
  'Paladin',
  'Ranger',
  'Fighter (Eldritch Knight)',
  'Rogue (Arcane Trickster)',
  'Warlock',
]

export const races = [
  'Dragonborn',
  'Dwarf',
  'Elf',
  'Gnome',
  'Half Elf',
  'Half Orc',
  'Halfling',
  'Human',
  'Tiefling',
  'Volo',
  'Aarakocra',
  'Aasimar',
  'Bug Bear',
  'Firbolg',
  'Goblin',
  'Grung',
  'Hobgoblin',
  'Kenku',
  'Kobold',
  'Lizardfolk',
  'Orc',
  'Tabaxi',
  'Triton',
  'Yuan-Ti Pureblood',
  'mToF',
  'Gith',
  'Unearthed Arcana',
  'Changeling',
  'Eladrin',
  'Genasi',
  'Goliath',
  'Minotaur (Krynn)',
  'Shifter',
  'Warforged (Eberron)',
  'Hombrewed',
  'Changeling (Variant)',
  'Chelone',
  'Drwell',
  'Elan',
  'Feykinn',
  'Gith (HB)',
  'Harssaf',
  'Hellborn',
  'Huldra(kall)',
  'Hylian',
  'Merfolk',
  'Mummy',
  'Olog-hai',
  'Pyrravyn',
  'Satyr',
  'Shadar-kai',
  'Tortle',
  'Velkarak',
  'Warforged (Elemental)',
]
